/* ─────────────────────────────────────────────
   data.js  —  All portfolio content lives here.
   Edit this file to update anything on the site.
   ───────────────────────────────────────────── */

const DATA = {

  /* ── PERSONAL ── */
  name:       "Tomás Lopera Duque",
  nameShort:  "Tomás Lopera",
  role:       "Data & AI Intern · Software Engineering Student",
  location:   "Colombia",
  university: "EIA University",
  github:     "https://github.com/Tomaslopera",
  linkedin:   "https://www.linkedin.com/in/tomaslopera/",  /* update with your real LinkedIn URL */

  /* Path to your CV PDF (place the file in the same folder as the HTML files).
     Set to null to hide the download button. */
  cvPath: "cv_tomas_lopera.pdf",

  /* bio: short line shown in the HERO section only */
  bio: "Passionate about building scalable data solutions that support analytics and AI use cases. Experienced in SQL, Python, ETL/ELT pipelines and AWS cloud services.",

  /* about: two separate paragraphs in the ABOUT strip on the home page */
  aboutWho:   "Data & AI Intern passionate about building scalable data solutions that support analytics and AI use cases. Skilled in data manipulation, exploratory analysis, data modeling, and foundational machine learning concepts.",
  aboutFocus: "Continuously expanding expertise in modern data engineering and cloud technologies — ETL/ELT pipelines, dimensional modeling, AWS orchestration, Lakehouse architectures, and intelligent AI agents using LLMs and RAG.",

  /* ── HERO STATS ── */
  stats: [
    { num: "20+",  label: "Projects",           desc: "Data Engineering, ML, AI Agents & BI",    color: "var(--blue-mid)"   },
    { num: "2x",   label: "Hackathon Finalist",  desc: "Winner + Runner-Up · EIA University",     color: "var(--teal-mid)"   },
    { num: "3x",   label: "NVIDIA Certified",    desc: "Deep Learning, NLP, Prompt Engineering",  color: "var(--green-mid)"  },
    { num: "2026", label: "Expected Graduation", desc: "Software Engineering · EIA University",   color: "var(--purple-mid)" },
  ],

  /* ── TECH STACK ── */
  stack: [
    { name: "Core Languages",    color: "var(--muted)",      chips: ["SQL", "Python", "Bash", "Java", "Git", "Docker"] },
    { name: "Data Engineering",  color: "var(--blue-mid)",   chips: ["Pandas", "Spark", "dbt", "Prefect", "Airflow", "Databricks", "Snowflake"] },
    { name: "AWS",               color: "var(--teal-mid)",   chips: ["IAM", "S3", "EC2", "VPC", "Lambda", "RDS", "Glue", "Redshift", "Athena", "SageMaker", "Textract", "API Gateway"] },
    { name: "Data Science & AI", color: "var(--purple-mid)", chips: ["scikit-learn", "SHAP", "LangChain", "Agents", "RAG"] },
    { name: "BI & Visualization", color: "var(--amber-mid)", chips: ["Power BI", "DAX", "Matplotlib", "Seaborn"] },
    { name: "Others",           color: "var(--coral-mid)",  chips: ["n8n", "FastAPI", "MySQL", "PostgreSQL", "React", "SQLAlchemy", "SQLServer"] },
  ],

  /* ── PROJECTS ── */
  projects: [
    { category: "Data Engineering", title: "AWS ETL + Data Warehouse + BI",
      role: "ETL flow design · AWS orchestration · Prefect & crontab · BI integration",
      description: "End-to-end pipeline for the Olist dataset using AWS and Prefect. Automates ETL from PostgreSQL (RDS) to S3, integrates Redshift Serverless via Glue, and connects the DW to PowerBI.",
      stack: ["Python", "Prefect", "RDS", "S3", "Glue", "Redshift", "Power BI", "Boto3"],
      repo: "https://github.com/Tomaslopera/AWS_ECommerce_DW" },
    { category: "Data Engineering", title: "ETL/ELT CoinGecko · Prefect",
      role: "Prefect decorators & custom tasks · AWS resources (S3, RDS)",
      description: "ETL/ELT flow to extract cryptocurrency data from CoinGecko's public API, transform with pandas, and persist in Parquet on S3 and/or PostgreSQL RDS.",
      stack: ["Prefect", "Python", "Pandas", "Boto3", "PyArrow", "PostgreSQL", "S3"],
      repo: "https://github.com/Tomaslopera/ETL-ELT_CoinGecko" },
    { category: "Data Engineering", title: "Colombian Export DW · DIAN",
      role: "ETL development · data modeling · AWS architecture design",
      description: "Data Warehouse for Colombian export data using DIAN's open datasets, built on a star schema with ETL in Python and cloud architecture on AWS.",
      stack: ["Python", "Pandas", "SQLAlchemy"],
      repo: "https://github.com/Tomaslopera/DIAN_Exportations" },
    { category: "Data Engineering", title: "Books to Scrape · ETL Pipeline",
      role: "ETL design · Selenium scraping · data modeling · PostgreSQL integration",
      description: "Automated ETL pipeline extracting, transforming, and loading book data using Selenium and BeautifulSoup. Data cleaned with Pandas and loaded into PostgreSQL.",
      stack: ["Python", "Selenium", "BeautifulSoup", "Pandas", "SQLAlchemy", "PostgreSQL"],
      repo: "https://github.com/Tomaslopera/BooksToScrape" },
    { category: "Data Engineering", title: "MovieLens Lakehouse · Databricks",
      role: "ETL pipeline design · Delta Lake modeling · Databricks notebooks",
      description: "Lakehouse architecture in Databricks using the MovieLens dataset, applying the Medallion model (Bronze → Silver → Gold) with Spark and Delta Lake.",
      stack: ["Databricks", "PySpark", "Delta Lake", "Medallion Architecture"],
      repo: "https://github.com/Tomaslopera/Databricks_Lakehouse" },
    { category: "Data Engineering", title: "Chicago Crimes Analytics · Snowflake + dbt",
      role: "dbt modeling (staging → intermediate → marts) · Snowflake · SQL transformations",
      description: "End-to-end analytics engineering using Chicago crime data, implementing ELT workflows with dbt on Snowflake following best practices.",
      stack: ["Snowflake", "dbt", "SQL", "ELT"],
      repo: "https://github.com/Tomaslopera/Chicago_Crimes" },
    { category: "Data Engineering", title: "Cybercrime Analytics · Snowflake + dbt",
      role: "dbt project structure · modular SQL transformations · Snowflake integration",
      description: "Analytics pipeline for cybercrime data using Snowflake and dbt, applying modular SQL transformations and data quality validations.",
      stack: ["Snowflake", "dbt", "SQL", "ELT"],
      repo: "https://github.com/Tomaslopera/Delitos_Informaticos" },
    { category: "Data Engineering", title: "ETL Contrataciones · Airflow + AWS",
      role: "ETL design & implementation · Airflow orchestration · AWS architecture",
      description: "Production-ready ETL pipeline for processing procurement data using Apache Airflow, designed for scalable cloud-based data workflows.",
      stack: ["Python", "Apache Airflow", "AWS", "ETL"],
      repo: "https://github.com/Tomaslopera/etl_contrataciones" },
    { category: "Data Science", title: "Telco Customer Churn · Classification",
      role: "EDA · preprocessing · SHAP feature selection · model comparison",
      description: "Binary classification to predict customer churn. Achieved ~84% accuracy with LR, KNN, Decision Tree, and Random Forest — robust pipeline with no data leakage.",
      stack: ["scikit-learn", "SHAP", "Pandas", "IterativeImputer"],
      repo: "https://github.com/Tomaslopera/Telco_Classification" },
    { category: "Data Science", title: "Financial Customer Segmentation · Clustering",
      role: "Cleaning/imputation/scaling · K-Means/DBSCAN/Hierarchical/GMM · cluster profiling",
      description: "Segmentation of a financial institution's customers for second card adoption, validating a 4-cluster hypothesis with Silhouette scoring.",
      stack: ["scikit-learn", "K-Means", "DBSCAN", "GMM", "Seaborn"],
      repo: "https://github.com/Tomaslopera/CasoAgrupamiento" },
    { category: "Data Science", title: "Intrusion Detection · Classification",
      role: "Pipeline MinMaxScaler + OneHotEncoder · LR/Tree/RF/SVM/GB · threshold tuning",
      description: "Binary classification for intrusion detection (Normal vs Attack). F1 ≥ 80% with cross-validation and threshold adjustment to minimize false negatives.",
      stack: ["scikit-learn", "Gradient Boosting", "SVM", "Pandas"],
      repo: "https://github.com/Tomaslopera/CasoClasificacion" },
    { category: "Data Science", title: "Insurance Premium Prediction · Regression",
      role: "EDA · feature engineering · scaling/encoding · R², MAE, RMSE, MAPE evaluation",
      description: "Prediction of insurance premiums based on demographic and lifestyle data, targeting MAPE ≤ 15%.",
      stack: ["scikit-learn", "Pandas", "Matplotlib", "Seaborn"],
      repo: "https://github.com/Tomaslopera/CasoRegresion" },
    { category: "Data Science", title: "Fuel Consumption Forecasting · Time Series",
      role: "SARIMAX · Linear Regression · Decision Trees · Random Forest · RNN",
      description: "Forecasting the 'Gasoleos' variable from the energy dataset. RNN achieved 4% MAPE and SARIMAX 8%.",
      stack: ["TensorFlow", "Statsmodels", "Skforecast", "scikit-learn"],
      repo: "https://github.com/Tomaslopera/TimeSeries_FuelConsumption" },
    { category: "AI", title: "AI Negotiation System · Hackathon Winner",
      role: "Data engineering & cleaning · RAG chatbot implementation",
      description: "AI-based negotiation system to assist customers with loan difficulties. EDA and data cleaning implemented in a RAG-powered chatbot for Sistecredito.",
      stack: ["Python", "RAG", "OpenAI", "Pandas"],
      repo: "https://github.com/Tomaslopera/Hackathon_Sistecredito" },
    { category: "AI", title: "Logistic Agent · Hackathon Runner-Up",
      role: "Dummy DB data engineering · n8n orchestration",
      description: "Logistics agent for Haceb's call center using n8n orchestration, ETL from Google Drive to Postgres (Supabase), vector-based retrieval, and OpenAI API.",
      stack: ["n8n", "Microsoft Power Automate", "OpenAI"],
      repo: "https://github.com/Tomaslopera/Hackathon_Haceb" },
    { category: "AI", title: "Genetic Algorithm · Financial Portfolios",
      role: "GA implementation (fitness, crossover, mutation, penalties) · yfinance pipeline",
      description: "Financial portfolio optimizer maximizing returns and minimizing risk using genetic algorithms.",
      stack: ["Python", "NumPy", "YFinance", "Matplotlib"],
      repo: "https://github.com/Tomaslopera/GeneticAlgorithm_FinancialPortfolio" },
    { category: "AI", title: "AgentKit Fintech Assistant · OpenAI",
      role: "Agent configuration · prompt engineering · data modeling · use-case design",
      description: "Financial AI agent using OpenAI Agent Builder and ChatKit to analyze client, product, and transaction data — investment recommendations and credit risk alerts.",
      stack: ["OpenAI Agent Builder", "ChatKit", "File Search", "Vector Store"],
      repo: "https://github.com/Tomaslopera/AgentKit_Fintech" },
    { category: "BI", title: "Power BI Projects · Dashboards",
      role: "Power Query · DAX · KPIs · maps · navigation",
      description: "Collection of dashboards solving business cases — video game sales, global indicators, HR analytics, and personal finance.",
      stack: ["Power BI", "DAX", "Power Query"],
      repo: "https://github.com/Tomaslopera/PowerBI_Projects" },
    { category: "Backend", title: "Recircular · Circular Economy Marketplace",
      role: "Relational schema & REST API for auth, publications and orders",
      description: "Circular economy marketplace for posting, buying, selling, and reusing materials. Full REST API with FastAPI and MySQL.",
      stack: ["React", "FastAPI", "MySQL"],
      repo: "https://github.com/Tomaslopera/Recircular" },
    { category: "Backend", title: "Parkhub · Parking Reservation App",
      role: "REST API & data model for users, reservations and reports",
      description: "Parking space reservation application with registration, login, password change, reservations, and history.",
      stack: ["React", "FastAPI", "MySQL"],
      repo: "https://github.com/Tomaslopera/ParkHub" },
    { category: "Cloud", title: "AWS Avianca Demo · Full Cloud Deployment",
      role: "AWS infrastructure · Cognito auth (PKCE) · Contentful CMS · Lambda + API Gateway backend",
      description: "Full deployment of an airline web app on AWS. Frontend hosted on S3 + CloudFront with OAC. Auth via Cognito (email, phone, Google, Facebook — PKCE flow). Dynamic content managed with Contentful. Backend powered by API Gateway, Lambda, and RDS. Integrated with Google Analytics and OpenShift.",
      stack: ["S3", "CloudFront", "Cognito", "API Gateway", "Lambda", "RDS", "Contentful", "Google Analytics", "OpenShift"],
      repo: "https://github.com/Tomaslopera/AWS_Avianca_Demo" },
  ],

  /* ── WORK EXPERIENCE (professional jobs) ── */
  work: [
    {
      company:     "Cadena SA",
      title:       "Data & AI Intern",
      period:      "Jan 2026 — Jul 2026",
      status:      "Active",
      description: "Working within the data and AI team on document intelligence and data pipeline development. Building automated workflows with AWS — Textract for OCR, S3 for storage, RDS for persistence, and Lambda for serverless processing.",
      stack:       ["Python", "SQL", "ETL", "Textract", "S3", "RDS", "Lambda"],
    },
  ],

  /* ── ACADEMIC EXPERIENCE (hackathons, research, university projects) ── */
  academic: [
    { org: "EIA University · Sistecredito", title: "AI Negotiation System", period: "03/2025",
      badge: "Hackathon Winner", badgeStyle: "winner",
      description: "Developed an AI-based negotiation system to assist customers with loan payment difficulties. EDA and data cleaning fed into a RAG-powered chatbot.",
      repo: "https://github.com/Tomaslopera/Hackathon_Sistecredito" },
    { org: "EIA University · Haceb", title: "Logistic Agent for Call Center", period: "08/2025",
      badge: "Runner-Up", badgeStyle: "runner",
      description: "Logistics agent responding in natural language about order status and inventory using n8n orchestration, ETL from Google Drive to Postgres (Supabase), and OpenAI API.",
      repo: "https://github.com/Tomaslopera/Hackathon_Haceb" },
    { org: "EIA University · Cadena SA", title: "Technical Data Sheet Validation", period: "06/2025 – 11/2025",
      badge: null,
      description: "Workflow extracting, validating, and highlighting key information from technical data sheets using AWS Textract, OpenCV, and Streamlit. Presented to the client with scientific documentation.",
      repo: "https://github.com/Tomaslopera/Reto_Cadena" },
    { org: "ISA", title: "Innovation Hackathon Participant", period: "05/2024",
      badge: null,
      description: "Data analysis of ISA's databases focused on improving maintenance of electrical towers and power distribution infrastructure.",
      repo: "https://github.com/Tomaslopera/Hackathon_ISA" },
    { org: "Softserve & NVIDIA", title: "Medical AI Agent · Hackathon Participant", period: "09/2025",
      badge: null,
      description: "Built an AI agent on AWS focused on medical symptom analysis. Used a BERT model from Hugging Face deployed on EC2 to give illness recommendations based on patient symptoms, with Amazon Bedrock for the AI layer and Lambda + API Gateway for the backend connection.",
      repo: null },
    { org: "Lienxo", title: "Researcher & Programmer · LED Lighting", period: "06/2024 – 08/2024",
      badge: null,
      description: "Research project involving LED light programming with the DMX protocol. Developed automation solutions for lighting control systems.",
      repo: null },
  ],

  /* ── EDUCATION ── */
  education: [
    { period: "2022 — 2026 (expected)", school: "Universidad EIA",
      degree: "Software & Computer Engineering · Undergraduate",
      detail: "Focus on Data Engineering, Data Science, and Artificial Intelligence. Coursework covers ETL/ELT pipelines, dimensional modeling, feature engineering, and AI agents powered by RAG and LLMs.",
      focus: ["Data Engineering", "Data Science", "Machine Learning", "AI Agents", "Cloud Architecture"],
      primary: true },
    { period: "2016 — 2021", school: "Colegio José María Berrio",
      degree: "High School · Academic Track",
      detail: "Foundation in sciences and mathematics, building the analytical and problem-solving base that led to a career in software and data engineering.",
      focus: [], primary: false },
  ],

  languages: [
    { name: "Spanish", level: "Native", style: "native" },
    { name: "English", level: "B2",     style: "b2"     },
  ],

  /* To add a new cert: copy any block, update the fields, and add a color.
     color options: var(--green-mid) | var(--blue-mid) | var(--purple-mid) | var(--teal-mid) | var(--amber-mid) */
  certifications: [
    { provider: "NVIDIA", date: "Sep 2025", color: "var(--green-mid)",
      name: "Fundamentals of Deep Learning",
      skills: ["Deep Learning", "PyTorch", "Neural Networks"],
      link: "https://learn.nvidia.com/certificates?id=WtrDHNh0RSKwXf9qJHsnbA" },
    { provider: "NVIDIA", date: "Sep 2025", color: "var(--green-mid)",
      name: "Building Transformer-Based NLP Applications",
      skills: ["NLP", "BERT", "LangChain", "Transformers"],
      link: "https://learn.nvidia.com/certificates?id=orZRVYt7SSiXpq0-ogUudQ#" },
    { provider: "NVIDIA", date: "Sep 2025", color: "var(--green-mid)",
      name: "Building LLM Applications With Prompt Engineering",
      skills: ["LangChain", "Prompt Engineering", "LLMs"],
      link: "https://learn.nvidia.com/certificates?id=k0zsEfJZTq613HxKZz9P7w#" },
  ],

  softSkills: ["Communication", "Teamwork", "Problem Solving", "Critical Thinking", "Strategic Planning", "Analytical Skills"],

};